sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - nightly
branches:
  only:
    - master
    - travis-ci
before_script:
  - cargo install mdbook
script:
  - mdbook build

deploy:
  provider: pages
  local-dir: mdbook
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
